version: "3.8"

services:
  motoserver:
    container_name: motoserver
    image: motoserver/moto
    environment:
      - TEST_SERVER_MODE=1
    ports:
      - "9000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  stepfunctions_local:
    container_name: stepfunctions_local
    image: amazon/aws-stepfunctions-local
    environment:
      - BATCH_ENDPOINT=http://motoserver:5000
      - LAMBDA_ENDPOINT=http://motoserver:5000
      - AWS_ACCOUNT_ID=123456789012
    ports:
      - "8083:8083"
