version: "3.8"

services:
  localstack:
    profiles: ["localstack"]
    container_name: aws
    image: localstack/localstack
    environment:
      - HOSTNAME_EXTERNAL=awsnet
      - SERVICES=sts,sns,sqs,lambda,events,ec2,s3,secretsmanager,stepfunctions,ssm,iam,batch,cloudwatch
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - AWS_DEFAULT_REGION=us-east-1
      - EAGER_SERVICE_LOADING=1
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SYNCHRONOUS_SNS_EVENTS=1
      - SYNCHRONOUS_SQS_EVENTS=1
      - LAMBDA_DOCKER_NETWORK=awsnet
      - BATCH_DOCKER_FLAGS=--network awsnet
    ports:
      - "9000:4566"
      - "8083:8083"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      awsnet:
        aliases:
          - awsnet
networks:
  awsnet:
    name: awsnet
    driver: overlay
    attachable: true
  motoserver:
    container_name: motoserver
    image: motoserver/moto:3.0.4
    environment:
      - MOTO_DOCKER_NETWORK_NAME=awsnet
      - MOTO_DOCKER_NETWORK_MODE=overlay
    ports:
      - "9000:5000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      awsnet:
        aliases:
          - awsnet
  stepfunctions_local:
    container_name: stepfunctions_local
    image: amazon/aws-stepfunctions-local
    environment:
      - BATCH_ENDPOINT=http://awsnet:5000
      - LAMBDA_ENDPOINT=http://awsnet:5000
      - AWS_ACCOUNT_ID=123456789012
    ports:
      - "8083:8083"
    networks:
      awsnet:
        aliases:
          - sfn.awsnet
networks:
  awsnet:
    name: awsnet
    driver: overlay
    attachable: true
