version: "3.8"
services:
  localstack:
    image: localstack/localstack@sha256:7c6635493185d25165979995fb073fd789c72b6d8b17ef3a70b798d55576732f
    ports:
      - "4566:4566"
    environment:
      - SERVICES=stepfunctions,batch,events,iam,ec2,lambda,cloudwatch,s3,sts,ssm,secretsmanager
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=local
