version: "3.8"

services:
  aws:
    container_name: aws
    image: localstack/localstack
    environment:
      - MOTO_DOCKER_NETWORK_NAME=awsnet
      - MOTO_DOCKER_NETWORK_MODE=overlay
      - HOSTNAME_EXTERNAL=awsnet
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=true
      - LAMBDA_DOCKER_NETWORK=awsnet
      - SERVICES=sfn,sts,sns,sqs,lambda,events,ec2,s3,secretsmanager,stepfunctions,ssm,iam,batch,cloudwatch
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - LOCALSTACK_API_KEY=$LOCALSTACK_API_KEY
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "9000:4566"
      - "8083:8083"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - localstack:/tmp/localstack
    restart: "no"
    networks:
      awsnet:
        aliases:
          - awsnet
networks:
  awsnet:
    name: awsnet
    driver: overlay
    attachable: true
volumes:
  localstack:
