name: SFN-WDL Integration Tests

on:
  push

env:
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # These specific values are mandatory, they are sent to lambda hard coded
  AWS_ACCESS_KEY_ID: role-account-id
  AWS_SECRET_ACCESS_KEY: role-secret-key
  AWS_SESSION_TOKEN: session-token
  AWS_DEFAULT_REGION: us-east-1

jobs:
  linters:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{runner.os}}-cache
      - name: Run linters
        run: source scripts/init_ci_runner.sh && make lint

  unit_tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{runner.os}}-cache
      - name: Run tests
        run: |
          source scripts/init_ci_runner.sh
          source environment.test
          docker pull ghcr.io/chanzuckerberg/swipe:latest
          docker build --cache-from ghcr.io/chanzuckerberg/swipe:latest -t ghcr.io/chanzuckerberg/swipe:$(cat version) .
          docker-compose pull
          scripts/run_mock_server.sh &
          for i in {1..60}; do if timeout 1 bash -c "echo > /dev/tcp/localhost/9000"; then break; elif [[ $i == 60 ]]; then exit 1; else sleep 1; fi; done
          make deploy-mock test

  terraform_format:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache
          key: ${{runner.os}}-cache
      - name: Check Terraform Format
        run: |
          make format
          git diff --exit-code

